Fixed score calculation: now correctly rounds to 100*n
britzl/towerz pull request #1
Opened 2023-10-16 20:01 UTC by matyuschenko

The score was close to number of boxes * 100, but not exactly (please see _before.png_ attached). Now it's always equal to number of boxes * 100 (please see _after.png_ attached).

Also, I call the height calculation (_max_height_ function) after the animation, as the number of boxes may be changing during the animation (if boxes are still falling).

<img src="https://github.com/britzl/towerz/assets/11616311/6dd02e9d-a81e-4b3d-ac7d-226804d7a792" alt="before" height="700"/> <img src="https://github.com/britzl/towerz/assets/11616311/ea8f95d0-7a0c-4b41-91d2-da7ce8b96439" alt="after" height="700"/>

2023-10-17 08:58 UTC, britzl commented on game/game.script
> +			msg.post("#hud", "update_score", { score = math.floor(max_height(self) + 0.5) * 100 })
Good addition! Could you please add a code comment here explaining the change (why you do floor and why you recalculate max_height)?

2023-10-17 08:58 UTC, britzl requested changes
See review comment

2023-10-17 19:49 UTC, matyuschenko commented on game/game.script
> +			msg.post("#hud", "update_score", { score = math.floor(max_height(self) + 0.5) * 100 })
Done! Please let me know if the comments are okay. I'll amend them if they aren't 🙂
https://github.com/britzl/towerz/pull/1/commits/8766177b4d6ec233e7dea00725e455623389112b

2023-10-17 19:52 UTC, matyuschenko commented
> See review comment
Done! I'd appreciate if you could take a look again
https://github.com/britzl/towerz/pull/1/commits/8766177b4d6ec233e7dea00725e455623389112b

2023-10-18 06:44 UTC, britzl approved these changes
Good job! Thanks!

2023-10-18 06:44 UTC, merged